In [1]:
import clip


clip.available_models()

/data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


['RN50',
 'RN101',
 'RN50x4',
 'RN50x16',
 'RN50x64',
 'ViT-B/32',
 'ViT-B/16',
 'ViT-L/14',
 'ViT-L/14@336px']

In [2]:
_MODELS = {
    "RN50": "https://openaipublic.azureedge.net/clip/models/afeb0e10f9e5a86da6080e35cf09123aca3b358a0c3e3b6c78a7b63bc04b6762/RN50.pt",
    "RN101": "https://openaipublic.azureedge.net/clip/models/8fa8567bab74a42d41c5915025a8e4538c3bdbe8804a470a72f30b0d94fab599/RN101.pt",
    "RN50x4": "https://openaipublic.azureedge.net/clip/models/7e526bd135e493cef0776de27d5f42653e6b4c8bf9e0f653bb11773263205fdd/RN50x4.pt",
    "RN50x16": "https://openaipublic.azureedge.net/clip/models/52378b407f34354e150460fe41077663dd5b39c54cd0bfd2b27167a4a06ec9aa/RN50x16.pt",
    "RN50x64": "https://openaipublic.azureedge.net/clip/models/be1cfb55d75a9666199fb2206c106743da0f6468c9d327f3e0d0a543a9919d9c/RN50x64.pt",
    "ViT-B/32": "https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt",
    "ViT-B/16": "https://openaipublic.azureedge.net/clip/models/5806e77cd80f8b59890b7e101eabd078d9fb84e6937f9e85e4ecb61988df416f/ViT-B-16.pt",
    "ViT-L/14": "https://openaipublic.azureedge.net/clip/models/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd88be6f7c2e0eca1737a03836/ViT-L-14.pt",
    "ViT-L/14@336px": "https://openaipublic.azureedge.net/clip/models/3035c92b350959924f9f00213499208652fc7ea050643e8b385c2dac08641f02/ViT-L-14-336px.pt",
}

model, _ = clip.load("ViT-B/32", device="cuda:1")
model, _ = clip.load("ViT-B/16", device="cuda:1")
model, _ = clip.load("ViT-L/14", device="cuda:1")

100%|███████████████████████████████████████| 338M/338M [00:36<00:00, 9.63MiB/s]
100%|███████████████████████████████████████| 335M/335M [00:34<00:00, 10.1MiB/s]


In [2]:
model, _ = clip.load("RN50", device="cuda:1")
model, _ = clip.load("RN101", device="cuda:1")
model, _ = clip.load("RN50x4", device="cuda:1")
model, _ = clip.load("RN50x16", device="cuda:1")
model, _ = clip.load("RN50x64", device="cuda:1")

In [1]:
import lpips
loss_fn_alex = lpips.LPIPS(net='alex') # best forward scores
loss_fn_vgg = lpips.LPIPS(net='vgg') # closer to "traditional" perceptual loss, when used for optimization

import torch
img0 = torch.zeros(1,3,64,64) # image should be RGB, IMPORTANT: normalized to [-1,1]
img1 = torch.zeros(1,3,64,64)
d = loss_fn_alex(img0, img1)

/data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(


Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]


/data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Loading model from: /data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/lpips/weights/v0.1/alex.pth
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]


/data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Loading model from: /data1/humw/anaconda3/envs/faceoff_v2/lib/python3.10/site-packages/lpips/weights/v0.1/vgg.pth


In [2]:
print(d)

tensor([[[[0.]]]], grad_fn=<AddBackward0>)


In [3]:
d1 = loss_fn_vgg(img0, img1)
print(d1)

tensor([[[[0.]]]], grad_fn=<AddBackward0>)


In [3]:
img0 = torch.zeros(1,3,64,64).requires_grad_(True)
img1 = torch.zeros(1,3,64,64)
d = loss_fn_alex(img0, img1)

In [4]:
d.backward()

In [5]:
img0.grad

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]]])

In [4]:
# 读取VGGFace下的图像，resize到224*224尺寸，保存到新的文件夹VGGFace_224下
import os
from PIL import Image

# 设置原始图像文件夹和目标文件夹路径
source_folder = '/data1/humw/Datasets/new-CelebA-HQ'
target_folder = '/data1/humw/Datasets/new-CelebA-HQ_224'

if not os.path.exists(target_folder):
    os.makedirs(target_folder)

# 遍历源文件夹中的所有文件
for id_name in os.listdir(source_folder):
    id_folder = os.path.join(source_folder, id_name)
    tgt_id_folder = os.path.join(target_folder, id_name)
    os.makedirs(tgt_id_folder, exist_ok=True)
    for sub_name in os.listdir(id_folder):
        sub_folder = os.path.join(id_folder, sub_name)
        tgt_sub_folder = os.path.join(tgt_id_folder, sub_name)
        os.makedirs(tgt_sub_folder, exist_ok=True)
        for filename in os.listdir(sub_folder):
            file_path = os.path.join(sub_folder, filename)
            img = Image.open(file_path)
            resized_img = img.resize((224, 224))  # 将图片大小调整为224x224
            new_filename = f"{filename}"
            save_path = os.path.join(tgt_sub_folder, new_filename)
            resized_img.save(save_path)  # 保存处理后的图片到新的文件夹中

In [5]:
!ln -s /data1/humw/Datasets/VGGFace2_224 /data1/humw/Codes/FaceOff/datasets

In [8]:
!ln -s /data1/humw/Datasets/new-CelebA-HQ_224 /data1/humw/Codes/FaceOff/datasets